### ISSUE TITLE
default libstdc++/libsupc++ should be 64-bit for x86_64

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/sdk-ng#121]
In SDK 0.10.3 & 0.11.0-alpha the x86_64-zephyr-elf/x86_64-zephyr-elf/libstdc++.a {libsupc++.a} should be a 64-bit target archive.  For some reason its 32-bit.

This causes problems when trying to link or use cmake with c++.

**Comment by dcpleung** [comment]
With the GCC spec change in master, this should not be an issue anymore. The compiler flag check will no longer fail `-lstdc++` so it would be included correctly.

**Comment by dcpleung** [comment]
On SDK 0.10.3, it should be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/19735.
