### ISSUE TITLE
Add aarch64-zephyr-elf target

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/sdk-ng#133]
Add aarch64-zephyr-elf target support, in preparation for Cortex-A AArch64 port.

**Comment by galak** [comment]
> Add aarch64-zephyr-elf target support, in preparation for Cortex-A AArch64 port.

@stephanosio will you look at doing this?

**Comment by stephanosio** [comment]
cc @carlocaione @timork @vladimir-podbrezsky

**Comment by stephanosio** [comment]
> @stephanosio will you look at doing this?

I will try if I have some time to spare after finishing #132- that is, unless @carlocaione or someone else who is currently working on AArch64 port wants to take this.

**Comment by carlocaione** [comment]
I could look at this but not high priority at the moment.

**Comment by galak** [comment]
Here's a starting point for it https://github.com/zephyrproject-rtos/sdk-ng/pull/134

**Comment by stephanosio** [comment]
I used `aarch64-zephyr-elf-gcc` from #134 (included in 0.11.0-alpha-5) to test the Cortex-R AArch64 port by @carlocaione today; it built and ran tests successfully without any problems.
