### ISSUE TITLE
Use SDK 0.11 for shippable

### ISSUE THREAD

**Issue by carlocaione** [zephyrproject-rtos/sdk-ng#155]
A lot of work currently being done on zephyr needs SDK 0.11. We need to use SDK 0.11 for `shippable` otherwise we get failures (see https://github.com/zephyrproject-rtos/zephyr/pull/20263)

**Comment by stephanosio** [comment]
For now, we are still in 2.1 feature merge freeze, so this will need to wait a bit.

zephyrproject-rtos/zephyr#20625 is going to add the latest SDK 0.11 alpha release to the CI image, so it can be used for testing (special handling is required in the build script to activate this though).

**Comment by carlocaione** [comment]
Thanks for the pointer to the zephyr issue (I wasn't aware that there was a story already open). Not trying to push this now, just wanted to track the issue.

**Comment by galak** [comment]
Closing this as we now have SDK 0.11.x in CI.
