### ISSUE TITLE
Upgrade GDB on xtensa_intel_s1000 to 8.3

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/sdk-ng#188]
See comments in PR #187 about testing of GDB 8.3.

**Comment by dcpleung** [comment]
`sample_controller` is using GDB 8.3. Do you mean `intel_s1000_crb` instead?

**Comment by galak** [comment]
> `sample_controller` is using GDB 8.3. Do you mean `intel_s1000_crb` instead?

yes
