### ISSUE TITLE
Why does qemu_riscv32 project builds with zephyr-sdk-0.11.1 but never launches on qemu when the sdk doesn't include the riscv32 toolchain?

### ISSUE THREAD

**Issue by musamaanjum** [zephyrproject-rtos/sdk-ng#197]

**Comment by galak** [comment]
Can you explain further what issue you are seeing?

**Comment by musamaanjum** [comment]
I'm using Zephyr's eclipse plugin to create projects. I've created the project of qemu_riscv32 and I've built it from the menu. It builds fine. But when I've launched it on the emulator, gdb gives the error that the expected xlength is 8, but this project's xlength if 4. So when I've checked the Zephyr SDK, there is no riscv32 toolchain which means qemu_riscv32 project shouldn't have built in the first place. It means there is some kind of bug present in the project creation of qemu_riscv32.

**Comment by stephanosio** [comment]
Closing stale issue.
