### ISSUE TITLE
build fails on MAC

### ISSUE THREAD

**Issue by ciminaghi** [zephyrproject-rtos/sdk-ng#21]
# bash-4 is needed
brew install bash help2man
git clone https://github.com/zephyrproject-rtos/sdk-ng.git
bash
export PATH=/usr/local/Cellar/binutils/2.31.1_2/bin:$PATH
./go.sh arm
/Volumes/CrossToolNGNew/crosstool-ng /Volumes/CrossToolNGNew
M       config/arch/x86.in
M       scripts/build/arch/x86.sh
HEAD is now at b82b8adb Merge pull request #984 from slash3g/master
INFO  :: *** Generating package version descriptions
INFO  :: Master packages: android-ndk autoconf automake avr-libc binutils cloog duma elf2flt expat gcc gdb gettext glibc-ports glibc gmp isl libelf libiconv libtool linux ltrace m4 make mingw-w64 mpc mpfr musl ncurses newlib strace uClibc zlib
INFO  :: Generating 'config/versions/android-ndk.in'
INFO  :: Generating 'config/versions/autoconf.in'
INFO  :: Generating 'config/versions/automake.in'
INFO  :: Generating 'config/versions/avr-libc.in'
INFO  :: Generating 'config/versions/binutils.in'
INFO  :: Generating 'config/versions/cloog.in'
.....
INFO  :: Generating comp_libs.in (menu)
INFO  :: *** Gathering the list of data files to install
INFO  :: *** Running autoreconf
configure.ac:244: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:245: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
INFO  :: *** Done!
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-apple-darwin18.0.0
checking host system type... x86_64-apple-darwin18.0.0
checking whether ln -s works... yes
.......
checking for working ncurses/curses.h... no
checking for working ncurses.h... yes
checking for Curses Panel library with panel.h... yes
checking for Curses Menu library with menu.h... no
checking for Curses Menu library with ncurses/menu.h... no
configure: error: menu library not found
make: *** No targets specified and no makefile found.  Stop.
/Volumes/CrossToolNGNew
Building arm
/Volumes/CrossToolNGNew/build/build_arm /Volumes/CrossToolNGNew/build
./go.sh: line 74: /Volumes/CrossToolNGNew/bin/ct-ng: No such file or directory
./go.sh: line 76: /Volumes/CrossToolNGNew/bin/ct-ng: No such file or directory
./go.sh: line 77: /Volumes/CrossToolNGNew/bin/ct-ng: No such file or directory
/Volumes/CrossToolNGNew/build
bash-4.4$ 

config.log attached
[config.log](https://github.com/zephyrproject-rtos/sdk-ng/files/2638916/config.log)

**Comment by ciminaghi** [comment]
Sorry, the initial \# was copied from my notes, H1 was unintended

**Comment by mrusme** [comment]
@ciminaghi there's an issue with your ncurses installation, as it cannot find the menu.h header file:

```
checking for Curses Menu library with ncurses/menu.h... no
configure: error: menu library not found
```

Maybe check that and run again?

**Comment by mrusme** [comment]
Just ran into the same issue. Solution is the following:

Install ncurses with brew. Then, before running the `./go.sh` command, do this:

```
export LDFLAGS="-L/usr/local/opt/ncurses/lib -L/usr/local/opt/gettext/lib"
export CPPFLAGS="-I/usr/local/opt/ncurses/include -I/usr/local/opt/gettext/include"
export PKG_CONFIG_PATH="/usr/local/opt/ncurses/lib/pkgconfig"
```

This should get the build started.

**Comment by mrusme** [comment]
@nashif I guess this issue can be closed. I can confirm there's nothing wrong with the SDK.

**Comment by ciminaghi** [comment]
Thanks for your help !
I have no mac here to check at the moment.
Will do that as soon as possible.

**Comment by galak** [comment]
> @nashif I guess this issue can be closed. I can confirm there's nothing wrong with the SDK.

What MacOS version did you guys build on?

**Comment by mrusme** [comment]
@galak 10.14.5

**Comment by ciminaghi** [comment]
On Mon, Jul 29, 2019 at 06:44:42AM -0700, Kumar Gala wrote:
> > @nashif I guess this issue can be closed. I can confirm there's nothing wrong with the SDK.
> 
> What MacOS version did you guys build on?
>
10.14.4

Davide

**Comment by ciminaghi** [comment]
On Sun, Jul 28, 2019 at 03:47:42PM -0700, ???????????? wrote:
> Just ran into the same issue. Solution is the following:
> 
> Install ncurses with brew. Then, before running the `./go.sh` command, do this:
> 
> ```
> export LDFLAGS="-L/usr/local/opt/ncurses/lib -L/usr/local/opt/gettext/lib"
> export CPPFLAGS="-I/usr/local/opt/ncurses/include -I/usr/local/opt/gettext/include"
> export PKG_CONFIG_PATH="/usr/local/opt/ncurses/lib/pkgconfig"
> ```
> 
> This should get the build started.
>
Davides-MacBook-Pro:sdk-ng davide$ brew install ncurses
==> Auto-updated Homebrew!
Updated 2 taps (osx-cross/avr and px4/px4).
==> New Formulae
osx-cross/avr/avarice      osx-cross/avr/avr-gcc@6    osx-cross/avr/avr-gdb
osx-cross/avr/avr-gcc@4    osx-cross/avr/avr-gcc@7
osx-cross/avr/avr-gcc@5    osx-cross/avr/avr-gcc@8

Warning: ncurses 6.1 is already installed and up-to-date
To reinstall 6.1, run `brew reinstall ncurses`


export LDFLAGS="-L/usr/local/opt/ncurses/lib -L/usr/local/opt/gettext/lib"
export CPPFLAGS="-I/usr/local/opt/ncurses/include -I/usr/local/opt/gettext/include"
export PKG_CONFIG_PATH="/usr/local/opt/ncurses/lib/pkgconfig"
./go.sh arm

.....


checking for objcopy... no
configure: error: missing required tool: gobjcopy objcopy
make: *** No targets specified and no makefile found.  Stop.
/Volumes/CrossToolNGNew
Building arm
/Volumes/CrossToolNGNew/build/build_arm /Volumes/CrossToolNGNew/build
./go.sh: line 74: /Volumes/CrossToolNGNew/bin/ct-ng: No such file or directory
./go.sh: line 76: /Volumes/CrossToolNGNew/bin/ct-ng: No such file or directory
./go.sh: line 77: /Volumes/CrossToolNGNew/bin/ct-ng: No such file or directory


Looks very similar to this one:

https://github.com/pfalcon/esp-open-sdk/issues/350

Adding

export PATH="/usr/local/opt/binutils/bin:$PATH"

before starting go.sh makes the build process go ahead for me.
And actually:

Davides-MacBook-Pro:sdk-ng davide$ which objcopy
/usr/local/opt/binutils/bin/objcopy


Maybe something is wrong with my binutils installation ?


Thanks
Davide

**Comment by mrusme** [comment]
@ciminaghi go to https://www.gnu.org/software/binutils/ and download the binutils source of the version that you already have installed via Homebrew. Then compile the the binutils but do not `make install`. When they finished compiling:

```
$ cp binutils/obj{dump,copy} /usr/local/bin
$ cp binutils/readelf /usr/local/bin
```

Then try again.

**Comment by mrusme** [comment]
BTW: I have to admit that I got the SDK compiled and the CrossToolNGNew built, but nevertheless I switched to Linux just because using all this on macOS is such a big PITA, and there's only so much that Zephyr can do ease the pain.
