### ISSUE TITLE
the arc gcc in zephyr sdk should be updated.

### ISSUE THREAD

**Issue by vonhust** [zephyrproject-rtos/sdk-ng#24]
In ARC's secureshield, some new instrucitons are introduced, e.g., sflag, sjli.  The current arc gcc (6.2.1 20160824) does not support these new instructions. 

So suggest to update zhe arc gcc in zephyr-sdk to the latest version of arc gcc.

**Comment by galak** [comment]
> In ARC's secureshield, some new instrucitons are introduced, e.g., sflag, sjli. The current arc gcc (6.2.1 20160824) does not support these new instructions.
> 
> So suggest to update zhe arc gcc in zephyr-sdk to the latest version of arc gcc.

We are building gcc 8.2.0 as part of sdk-ng for ARC.
