### ISSUE TITLE
python 3.8 dependencies for ARC

### ISSUE THREAD

**Issue by jacoba-at** [zephyrproject-rtos/sdk-ng#297]
Hi,
I'm trying to run GDB for ARC from SDK 0.11.4 and I get the following error:
/tools/sw/zephyr-sdk-0.11.4/arc-zephyr-elf/bin/arc-zephyr-elf-gdb: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

Is there a dependency on python 3.8? I didn't see that when I installed Zephyr or Zephyr SDK on my Ubuntu 18.04 machine.

Thanks,
Jacob

**Comment by galak** [comment]
> Hi,
> I'm trying to run GDB for ARC from SDK 0.11.4 and I get the following error:
> /tools/sw/zephyr-sdk-0.11.4/arc-zephyr-elf/bin/arc-zephyr-elf-gdb: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
> 
> Is there a dependency on python 3.8? I didn't see that when I installed Zephyr or Zephyr SDK on my Ubuntu 18.04 machine.
> 
> Thanks,
> Jacob

If you look in the release notes you'll see comments about GDB & python:


```
  - Changed python support to build against python3.8.  This is an attempt to
    have the python support work on a larger number of distributions.

    NOTE: This may require install a python3.8 package on your system if
    python3.8 is not available.  On fedora systems that can be accomplished by:

    `sudo dnf install python38`

    On ubuntu systems that can be accomplished by:

    `sudo apt get install python3.8-dev`

```
