### ISSUE TITLE
Need to unify release and tag names

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/sdk-ng#32]
We seem to use different "version" formats for file name, tag, etc.  Need to clean this up so its the same everywhere.

**Comment by galak** [comment]
For example the URL to get the beta4 release is:

https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.10.0-beta4/zephyr-sdk-0.10-beta4-setup.run

```
 dirname: v0.10.0-beta4
filename: 0.10-beta4
     tag: v0.10.0-beta4
```

**Comment by nashif** [comment]
yeah, I am aware of this, will address.

**Comment by nashif** [comment]
beta5 now building hopefully with consistent versioning:

https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.10.0-beta5

**Comment by nashif** [comment]
btw, the tag does have a v prefix, similar to what we do in zephyr, the directory name on github is the tag name but the version string in the sdk name and elsewhere is now consistent.
