### ISSUE TITLE
FLASH and RAM consumption increase for 0.13.0-rc3

### ISSUE THREAD

**Issue by r2r0** [zephyrproject-rtos/sdk-ng#381]
After switching from SDK 0.12.4 to 0.13.0-rc3 I observed non neglible increase of FLASH and RAM usage.

FLASH usage increased about 5.7%
RAM usage increased about 1.3%

My app is hosted on Cortex-M4 (STM32WB55) and consists of mix of C and C++ (17) modules (no exceptions and no RTTI) with "optimize for size" enabled, last Zephyr commit from 29th Jul.

**Comment by stephanosio** [comment]
Duplicate of #369.
