### ISSUE TITLE
Bump GCC to 11.x

### ISSUE THREAD

**Issue by abrodkin** [zephyrproject-rtos/sdk-ng#408]
GCC 11.1 was released half a year ago with multiple improvements & fixes.
More information about GCC 11 release series could be found here: https://gcc.gnu.org/gcc-11/changes.html

So I guess it would be good to update GCC version in a newer Zephyr SDK.

**Comment by tejlmand** [comment]
Toolchain WG [2021-11-01]: @abrodkin will take a look at needed work for updating Zephyr SDK tro be based on GCC v11

**Comment by stephanosio** [comment]
superseded by #465
