### ISSUE TITLE
Update GNU toolchain components (Binutils, GCC, GDB) for H1 2022

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/sdk-ng#409]
### Rationale

Update the GNU toolchain components (Binutils, GCC, GDB) to the latest release in H1 2022.

Binutils 2.38, GCC 12.1 and GDB 12.1 will include some major enhancements including:
* Binutils: ARMv9-A architecture support
* Binutils: Support for new ARM cores such as Cortex-R52+, Cortex-A510, Cortex-A710 and Cortex-X2
* Binutils, GCC: RISC-V B extension support
* GDB: ARM M-Profile Vector Extension (MVE) support

**Expected release schedule**
* Binutils 2.38 - February 2022
* GCC 12.1 - April 2022
* GDB 12.1 - ~~TBD (maybe June 2022?)~~ May 2022 (they expedited this release somehow ..)

p.s. It may be desirable to consider updating to GDB 11.x if the GDB 12.1 release gets delayed since we are currently using a very old GDB release (9.2).

### Implementation Plan

**Target versions**

* Binutils 2.38
* GCC 12.1
* GDB ~~11.2~~ 12.1

~~Note that there is no concrete release schedule planned for GDB 12.1 yet, so we will be upgrading to GDB 11.2 first because the current GDB version of 9.2 is fairly old.~~ [GDB 12.1 has been released!](https://lists.gnu.org/archive/html/info-gnu/2022-05/msg00000.html).

- [x] #466
- [x] #465 
- [x] #467

**Comment by stephanosio** [comment]
@abrodkin @evgeniy-paltsev I am planning to update the toolchain versions this month as proposed in this issue. Can you provide the ARC patches based on the following GNU toolchain versions:

* Binutils 2.38
* GCC 12.1
* GDB 11.2

**Comment by abrodkin** [comment]
@stephanosio Binutils & GDB changes for ARC (both ARCv2 & ARCv3) are ready:
* Binutils based on upstream 2.38: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/zephyr-sdk-binutils-2.38
* GDB based on upstream 12.1: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/zephyr-sdk-gdb-12.1
ARC changes might be either squashed into 1 commit per repo or applied as existing series (in Binutils repo there's indeed just 1 cumulative patch which adds ARCv3).

GCC rebased on upstream 12.1 will be ready in coming weeks.

**Comment by stephanosio** [comment]
Temporarily disabled ARC targets because the ARC patch for GCC 12.1 is currently missing (tracked in https://github.com/zephyrproject-rtos/sdk-ng/issues/496).

**Comment by stephanosio** [comment]
Done (except ARC; see #496)
