### ISSUE TITLE
Add separate QEMU build for ARC

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/sdk-ng#445]
Add a separate QEMU build for ARC emulation because the ARC support has not been upstreamed yet and it is hard to keep the upstream QEMU and the ARC fork in sync.

The separate ARC QEMU build should be added in the same manner as the [`xilinx-qemu`](https://github.com/zephyrproject-rtos/sdk-ng/tree/main/meta-zephyr-sdk/recipes-devtools/xilinx_qemu).

The ARC QEMU shall:

* Build directly using the source from the [ARC QEMU fork repository](https://github.com/foss-for-synopsys-dwc-arc-processors/qemu)
* Be named `arc_qemu` (recipe).
* Provide `qemu-system-arc` and `qemu-system-arc64` symlinks under `(SYSROOT)/usr/bin`

Related discussion: https://github.com/zephyrproject-rtos/sdk-ng/pull/421#issuecomment-1065085098

**Comment by stephanosio** [comment]
cc @abrodkin

**Comment by abrodkin** [comment]
@stephanosio care to make me an assignee?

**Comment by stephanosio** [comment]
> @stephanosio care to make me an assignee?

I was planning to implement this since it is pretty simple thing to do, but it is also ok if you are willing to take this.

**Comment by abrodkin** [comment]
Well, I think I may do it real quick. Also it will be easier if I manage the versioning, i.e. create tags in our repo to use in the SDK etc.
And while at it, I'm wondering if https://github.com/zephyrproject-rtos/sdk-ng/blob/main/meta-zephyr-sdk/recipes-devtools/qemu/files/cross.patch is really needed? It's missing in Xtensa's QEMU recipe, so may be drop it from the generic patches? Or do I need to add it for ARC QEMU as well?

**Comment by stephanosio** [comment]
> I'm wondering if https://github.com/zephyrproject-rtos/sdk-ng/blob/main/meta-zephyr-sdk/recipes-devtools/qemu/files/cross.patch is really needed? It's missing in Xtensa's QEMU recipe, so may be drop it from the generic patches? Or do I need to add it for ARC QEMU as well?

The Xilinx QEMU is based on an older QEMU version that predates the switchover to meson. Since ARC QEMU uses meson, this patch will likely be needed.

**Comment by abrodkin** [comment]
@stephanosio do you have a branch of the SDK-ng with QEMU 6.2?
There're a couple of things which needs to be fixed:
1. `cross.patch` needs to be regenerated manually
2. What's worse Poky's `meson` needs to be bumped to 0.58.2+ as otherwise configuration fails with `ERROR: Meson version is 0.55.1 but project requires >=0.58.2`

(2) might be fixed by the Poky version bump, but which one to use? Currently we have "yocto-3.2.3" or "gatesgarth-24.0.3". "hardknott" seems to have meson 0.59.1.

That said it makes sense to add my work on top of previous QEMU 6.2 integration if it exists.

**Comment by stephanosio** [comment]
> 1. `cross.patch` needs to be regenerated manually

https://github.com/zephyrproject-rtos/sdk-ng/pull/421/files#diff-1d963e71010117efb6ec3983cbf0d11345c0e57879a74b46b8fafd0b232c7174

> 2\. What's worse Poky's `meson` needs to be bumped to 0.58.2+ as otherwise configuration fails with `ERROR: Meson version is 0.55.1 but project requires >=0.58.2`

I will look into manually updating it in #421, so you will not need to do it in the ARC QEMU PR.

Upgrading Yocto is a bit tricky because there has been a recent syntax change that makes upgrading a lot of effort, and we will be dropping Yocto/OE soon, so I would not want to spend too much time on that.

**Comment by abrodkin** [comment]
Ok, then ARC part should be all here: https://github.com/abrodkin/sdk-ng/commit/c93ada2bb5acc77106630813c648971428421db6

Once meson problem is solved, I guess we may cherry-pick/rebase this commit and should be OK.

**Comment by stephanosio** [comment]
> Ok, then ARC part should be all here: [abrodkin@c93ada2](https://github.com/abrodkin/sdk-ng/commit/c93ada2bb5acc77106630813c648971428421db6)
> 
> Once meson problem is solved, I guess we may cherry-pick/rebase this commit and should be OK.

Should be a separate PR. Also the ARC QEMU installation needs to be under a separate prefix so as to not overwrite the upstream QEMU files (as done in Xilinx).

I can provide further review in the PR.

**Comment by stephanosio** [comment]
@abrodkin I have added the patch you provided above, with some modifications, in #421.

**Comment by stephanosio** [comment]
Addressed in #421.
