### ISSUE TITLE
Broken links in releases 

### ISSUE THREAD

**Issue by kriku** [zephyrproject-rtos/sdk-ng#613]
Looks like links to release artefacts is broken:

<img width="965" alt="Screenshot 2022-12-24 at 10 59 12" src="https://user-images.githubusercontent.com/6429161/209426819-36119877-cd7b-430a-80b5-75ccb2192050.png">

https://github.com/zephyrproject-rtos/sdk-ng/releases

**Comment by stephanosio** [comment]
This is a GitHub bug. The link will work once you go into a specific release.
