### ISSUE TITLE
MVE vcmpq vector-scalar can trigger ICE (GCC PR107987)

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/sdk-ng#625]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107987

Just a reminder to apply the following patch to our upcoming GCC 12.2 fork:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=27b6fb155dfefae8dc6ac8d8264851f104dff4e4

**Comment by gromero** [comment]
@stephanosio Thank you!
