### ISSUE TITLE
ARC toolchain support

### ISSUE THREAD

**Issue by abrodkin** [zephyrproject-rtos/sdk-ng#7]
Since the following commit https://github.com/crosstool-ng/crosstool-ng/commit/62f5b90e2e79a8ccee07534f9484627e5e268d50 it's possible to build multilibbed Elf32 (AKA baremetal) toolchain for ARC.

Latest Binutils (2.30), GCC (8.1.0) and GDB (8.1) are recommended to be used for ARC.
But given versions mentioned above are all available in up-to-date Crosstool-NG and moreover they are default versions now there should be no problem with it.

**Comment by nashif** [comment]
thanks
