### ISSUE TITLE
Releases page does not have links to the full version

### ISSUE THREAD

**Issue by edwardalee** [zephyrproject-rtos/sdk-ng#713]
This looks like a very easy problem, but the [releases page](https://github.com/zephyrproject-rtos/sdk-ng/releases/) does not have links to the full version.  It looks like the text that looks like this:
```
[AArch64][zephyr-sdk-0.16.3_linux-aarch64.tar.xz]
```
should instead look like this:
```
[AArch64](zephyr-sdk-0.16.3_linux-aarch64.tar.xz)
```

**Comment by stephanosio** [comment]
Please see #613.
