### ISSUE TITLE
Release downloads disappearing

### ISSUE THREAD

**Issue by SeppoTakalo** [zephyrproject-rtos/sdk-ng#827]
Hi,

From the download page, 0.17.0 minimal linux package seem to be missing
https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.17.0/zephyr-sdk-0.17.0_linux-x86_64_minimal.tar.xz

I got 404 error from that URI.

**Comment by stephanosio** [comment]
The deployment CI run was still in progress at the time. It should work now.
