### ISSUE TITLE
What is the mearning for NG, PR, and CI?

### ISSUE THREAD

**Issue by jiapei100** [zephyrproject-rtos/sdk-ng#87]
1. Crosstool **NG**
What does **NG** represent for?

2. **PR** Builds
What does **PR** mean?

3. One the release is created, **CI** will build the SDK image and will upload it to the release page.
What does **CI** represent for?

**Comment by aescolar** [comment]
NG: Next Generation
PR: Pull Request
CI: Continuous Integration
