### ISSUE TITLE
when SDK installer is run by normal user, default install path should be wirtable by user

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/sdk-ng#99]
often users of the SDK run the installer as normal users but get the default install path as a system folder. When running as a normal user (no sudo) the default path should be user-writable.

**Comment by galak** [comment]
change default install to $HOME/zephyr-sdk/

**Comment by galak** [comment]
Trying to address this with PR https://github.com/zephyrproject-rtos/sdk-ng/pull/112

**Comment by galak** [comment]
Merged PR #112, we now default to $HOME/zephyr-sdk for install.
